# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e18262fb5d97a77471c1e0a48c2985525d110aa6234fd07ac9041fce4081bb5da4f94249fe8326a2a633c2ee65df4cb28b3fd941190ff6d7e5a9d5c18d1b548

test:
  secret_key_base: 356776e8cab307e95bbda4a4dd5f9500d4e72c4702f279247a3bc2c2dd9fdd433a8ff2237a4a790fa0e294b97b97223ec767d06472186204bfb4c47ea39ccde8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
